---
ip: "192.168.10.17"
name: tao
hostname: tao
cpus: 1
memory: 2048
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: "/Users/alroniks/Code"
      to: "/home/vagrant/Code"

databases:
    - tao

sites:
    - map: tao.loc
      to: /home/vagrant/Code/tao
      install: true
      username: admin
      password: admin
      ext: 'taoCe,taoDevTools'
      type: tao
      php: 5
